AWSTemplateFormatVersion: "2010-09-09"
Description: This is the first Cloud Formation template to create s3 Bucket
Resources:
  mohans3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: demobucketdata00001
      PublicAccessBlockConfiguration:
           BlockPublicAcls: false
           BlockPublicPolicy: false
           IgnorePublicAcls: false
           RestrictPublicBuckets: false
  MyBucketPolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
          Bucket:
            Ref: 'mohans3bucket'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
             - Effect: Allow
               Principal: '*'
               Action: 's3:GetObject'
               Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: 'mohans3bucket'
                    - '/*'
  myec2instance:
       Type: AWS::EC2::Instance
       Properties:
          ImageId: ami-084568db4383264d4
          InstanceType: t2.micro